#!/usr/bin/with-contenv sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

echo "$APP_NAME's memory consumption comes very close to its limit."

# vim: set ft=sh :
