#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

echo "$APP_NAME's memory consumption comes very close to its limit."

# vim:ft=sh:ts=4:sw=4:et:sts=4
