#!/usr/bin/with-contenv sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

export LD_LIBRARY_PATH=$CRASHPLAN_DIR

FULL_CP="$CRASHPLAN_DIR/lib/com.backup42.desktop.jar:$CRASHPLAN_DIR/lang:$CRASHPLAN_DIR"

source $CRASHPLAN_DIR/bin/run.conf

echo "Starting CrashPlan Engine..."
cd $CRASHPLAN_DIR
exec $APP_NICE_CMD s6-setuidgid $USER_ID:$GROUP_ID $JAVACOMMON $SRV_JAVA_OPTS -classpath $FULL_CP com.backup42.service.CPService >> /config/log/engine_output.log 2>> /config/log/engine_error.log

# vim: set ft=sh :
