#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

LINE="$1"

if echo "$LINE" | grep -q " Unable to add watch for path "; then
    if echo "$LINE" | grep -q " errno: , 13"; then
        # Exclude inotify errors related to improper permissions.  These are
        # handled by another notification.
        exit 1
    fi
    exit 0
fi

# No match found.
exit 1

# vim: set ft=sh :
